### ISSUE TITLE
Add support for private apigw

### ISSUE THREAD

**Issue by thedent** [ramgrandhi/serverless-wso2-apim#47]
The current setup only supports https and jms backend. The current WSO2 installation we are working with also has support for apigw private endpoints. To solve this we need to be able to populate the `endpoint_type: 'lambda`.  I know this is custom to our installation so I propose a solution where we are able to override the `endpoint_type`

I propose the following changes to the serverless plugin:

```yaml
wso2apim:
  apidefs:
    - myApi:
        backend:
          endpointType: lambda
```

Snippet captured in developer tools:
```js
const example = {
   production_endpoints: { url: 'https://228u8q9451.execute-api.eu-west-1.amazonaws.com/dev', endpoint_type: 'lambda', 
   template_not_supported: false },
   endpoint_type: 'lambda',
};
```
